#!/bin/bash
echo
echo "Starting Database Deployment ..."
echo
kubectl apply -f mysql/ns.yml
kubectl apply -f mysql/secret.yml
kubectl apply -f mysql/pvc.yml
kubectl apply -f mysql/service.yml
kubectl apply -f mysql/deployment.yml

echo
echo 
echo "Starting Application Deployment ..."
kubectl apply -f restapi/ns.yml
kubectl apply -f restapi/secret.yml
kubectl apply -f restapi/configMap.yml
kubectl apply -f restapi/service.yml
kubectl apply -f restapi/deployment.yml