# Database Password
apiVersion: v1
data:
  sql-password: Ym9va3N0b3JlLXBhc3N3b3Jk
kind: Secret
metadata:
  name: mysql-password
  namespace: restapi

---
# Database User Name
apiVersion: v1
data:
  sql-user: Ym9va3N0b3JlLXVzZXI=
kind: Secret
metadata:
  name: mysql-user
  namespace: restapi

--- 
# Database Name
apiVersion: v1
data:
  sql-db: Ym9va3N0b3Jl
kind: Secret
metadata:
  name: mysql-db
  namespace: restapi