apiVersion: v1
kind: Service
metadata:
  labels:
    app: restapi
  name: restapi
  namespace: restapi
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: restapi
status:
  loadBalancer: {}